### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by frroossst** [frroossst/Delisle#1]
- [ ] Listen and Send CAN bus signals
- [ ] Respond to signals according to pre-defined structures
- [ ] Macro to parse toml file at compile time on host
- [ ] Add support for I2C, SPI
